---
title: "ADMH coding"
author: "Anna Andreychenko"
date: "`r Sys.Date()`"
output: html_document
---

<style type="text/css">
body{
  font-family: Helvetica;
  font-size: 12pt;
}
/* Headers */
h1, h2{
  font-size: 16pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(openxlsx)
library(lubridate)
```

Первым делом подгрузим все нужные нам файлы:

- MH_MEDICALHISTORY.xlsx, 

- ADSL.xlsx, 


```{r upload}


mh_ds <- read.xlsx("./SDTM/MH_MEDICALHISTORY.xlsx")

adsl_ds <- read.xlsx("./ADaM-like/ADSL.xlsx")


```

Поработаем с файлом ADSL, вытащим оттуда переменные:

-STUDYID;
-USUBJID
-TRTP;
-TRTPN;


```{r dm}
adsl_data <- 
  adsl_ds %>% 
  select(STUDYID, SUBJID, USUBJID, 
         TRTP, TRTPN) %>% 
  mutate(STUDYID = as.character(STUDYID),
         USUBJID = as.character(USUBJID),
         TRTP = as.character(TRTP),
         TRTPN = as.integer(TRTPN))
```

Данные из домена МН:

MHSEQ 
MHCAT
MHTERM 
MHDECOD 
MHBODSYS




```{r mh_data}
mh_data <- 
  mh_ds %>% 
  filter(MHCAT == "Medical History") %>%
  select(STUDYID, SUBJID, MHSEQ, MHCAT, 
         MHTERM, MHDECOD,MHBODSYS) %>% 
  mutate(MHSEQ = as.integer(MHSEQ),
         MHCAT = as.character(MHCAT),
         MHTERM = as.character(MHTERM),
         MHDECOD = as.character(MHDECOD),
         MHBODSYS = as.character(MHBODSYS))

  
```
Даты
MHSTDTC


```{r ds_dates}
dates_data <- 
  mh_ds %>% 
  select(STUDYID,SUBJID,MHSEQ, MHENRTPT, MHSTDTC,MHENDTC) %>%
  mutate(MHSTDTC = as.character(MHSTDTC),
         MHSEQ = as.integer(MHSEQ),
         ASTDT = ifelse(nchar(MHSTDTC) == 4, format(as.Date(paste(MHSTDTC,"-01-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"), ifelse(nchar(MHSTDTC) == 7, format(as.Date(paste(MHSTDTC,"-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"),format(as.Date(MHSTDTC, format = "%Y-%m-%d"),"%d.%m.%Y"))),
         ASTDTF = ifelse(is.na(MHSTDTC),'Y',
                         ifelse(nchar(MHSTDTC) == 4, 'M', 
                        ifelse(nchar(MHSTDTC) == 7,'D',""))),
         MHENDTC = as.character(MHENDTC),
         AENDT = ifelse(MHENRTPT == 'ONGOING',"",  ifelse(nchar(MHENDTC) == 4, format(as.Date(paste(MHENDTC,"-01-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"), ifelse(nchar(MHENDTC) == 7, format(as.Date(paste(MHENDTC,"-01", sep=""), 
                                  format = "%Y-%m-%d"), 
                          "%d.%m.%Y"),format(as.Date(MHENDTC, format = "%Y-%m-%d"),"%d.%m.%Y")))),
         AENDTF = ifelse(is.na(MHENDTC),'Y',
                         ifelse(nchar(MHSTDTC) == 4, 'M', 
                        ifelse(nchar(MHSTDTC) == 7,'D',""))),
         MHENRF = ifelse(MHENRTPT == 'ONGOING','ONGOING',"")
         ) 
  
                          
                         
```

```{r joins}
ADMH <- left_join(adsl_data, mh_data)
ADMH <- left_join(ADMH, dates_data)
ADMH$SUBJID <- NULL
ADMH <- filter(ADMH, !is.na(MHTERM))
ADMH <- ADMH[,c("STUDYID","USUBJID","TRTP","TRTPN","MHSEQ", "MHCAT","MHTERM",
                "MHDECOD", "MHBODSYS", "MHSTDTC", "ASTDT", "ASTDTF", "MHENDTC",
                "AENDT", "AENDTF", "MHENRTPT", "MHENRF")]
```
```{r}
write.xlsx(ADMH, "./ADaM-like/ADMH.xlsx")
```
