---
title: "BI_retraining_datavis_2024_HW1"
author: "Anna Andreychenko"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE, fig.width=16, fig.height=10)

library(tidyverse)
```

## Data reading

```{r dataLoading}
hogwarts <- read_csv("data/hogwarts_2024.csv")

```

```{r}

# Changing some variables type to factors
hogwarts <- hogwarts |> mutate(
  across(c(house, course, sex, wandCore, bloodStatus), ~ as.factor(.x))
)
```

# Решения заданий

## Столбчатые диаграммы

### Задание 1

```{r}
ggplot(hogwarts)+
  geom_bar(aes(x = course), fill = "maroon4", colour = "olivedrab")+
  theme_classic()
```

### Задание 2

```{r}
ggplot(hogwarts)+
  geom_bar(aes(x = fct_infreq(house), 
               fill = bloodStatus), 
           colour = "black", 
           position = "fill")+ 
  scale_x_discrete(name = "house")+
  theme_classic()
```

**Вывод:** В каждом из факультетов больше половины студентов являются полукровками.

### Задание 3

```{r}
theme_custom = theme(axis.text.x = element_text(size = 24), axis.title.x = element_text(size = 26),
        axis.text.y = element_text(size = 24), axis.title.y = element_text(size = 26),
        legend.text = element_text(size=20), legend.title = element_text(size=24))

ggplot(subset(hogwarts, bloodStatus != "half-blood"))+
  geom_bar(aes(x = fct_infreq(house), 
               fill = bloodStatus), 
           colour = "black", 
           position = "fill")+ 
  scale_x_discrete(name = "Факультет")+
  geom_hline(yintercept = 0.5, linetype = 'dashed', linewidth = 2.0, col = 'red')+
  labs(y = "Доля")+
  scale_fill_discrete(name = "Статус по крови", labels = c("Маглорожденные", "Чистокровные"))+
  theme_classic()+
  theme_custom
```

## Боксплоты

### Задание 1

```{r}
hogwarts |> 
  select(id, `house`, `week_3`) |> 
  ggplot()+
  geom_boxplot(aes(x = fct_reorder(house, week_3, .fun="median", .desc = TRUE),
                   y = week_3))+
  scale_x_discrete(name = "Факультет")+
  theme_bw()+
  theme_custom
```

### Задание 2

```{r, fig.width=14, fig.height = 14 }
hogwarts |> 
  select(id, `house`, `bloodStatus`, `week_3`) |> 
  ggplot(aes(x = fct_reorder(house, week_3, .fun="median", .desc = TRUE), y = week_3, fill = bloodStatus))+
  geom_boxplot(notch = TRUE) +
  scale_x_discrete(name = "Факультет")+
  labs(y = "Оценки, неделя 3")+
  scale_fill_discrete(name = "Статус по крови", labels = c("полукровные", "Маглорожденные", "Чистокровные"))+
  theme_bw()+
  theme_custom
```

### Задание 3

```{r, fig.width=28, fig.height = 14 }
hogwarts |> 
  select(id, `house`, `bloodStatus`, `week_3`) |> 
  ggplot(aes(x = fct_reorder(house, week_3, .fun="median", .desc = TRUE), y = week_3, fill = bloodStatus))+
  geom_boxplot(notch = TRUE, 
               outliers = FALSE, 
               varwidth = TRUE, 
               staplewidth = 0.5, 
               linetype = 1,
               lwd = 1.5)+
  geom_jitter()+
  scale_x_discrete(name = "Факультет")+
  labs(title = "Распределение оценок за 3ью неделю", y = "Оценка")+
  scale_fill_discrete(name = "Статус по крови", labels = c("Полукровные", "Маглорожденные", "Чистокровные"))+
  theme_bw()+
  theme_custom +
  theme(plot.title = element_text(face = "bold", size = 30, hjust = 0.5))
```
